// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

    // SCREEN: ui_WiFiScreen
    extern void ui_WiFiScreen_screen_init(void);
    extern void ui_WiFiScreen_screen_destroy(void);
    extern lv_obj_t *ui_WiFiScreen;

    extern void ui_event_btnWiFiConnect(lv_event_t *e);
    extern lv_obj_t *ui_btnWiFiConnect;

    extern void ui_event_btnWiFiBack(lv_event_t *e);
    extern lv_obj_t *ui_btnWiFiBack;

    extern lv_obj_t *ui_lblWifiTitle;
    extern lv_obj_t *ui_lblWifiStatus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
