// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

#include <string.h>

#include "wifi_manager.h"

lv_obj_t *ui_WiFiScreen = NULL;

lv_obj_t *ui_btnWiFiConnect = NULL;
lv_obj_t *ui_btnWiFiBack = NULL;

lv_obj_t *ui_lblWifiTitle = NULL;
lv_obj_t *ui_lblWifiStatus = NULL;

static void ui_event_WiFiScreen(lv_event_t *e);

static lv_obj_t *ui_taWifiSsid;
static lv_obj_t *ui_taWifiPassword;
static lv_obj_t *ui_kbWifi;

static lv_timer_t *s_wifi_status_timer;
static char s_last_status[32];

static void wifi_status_timer_cb(lv_timer_t *timer)
{
    (void)timer;

    if (!ui_lblWifiStatus)
    {
        return;
    }

    char status[32];
    wifi_manager_get_status_text_copy(status, sizeof(status));

    if (strncmp(status, s_last_status, sizeof(s_last_status)) != 0)
    {
        strncpy(s_last_status, status, sizeof(s_last_status));
        s_last_status[sizeof(s_last_status) - 1] = '\0';
        lv_label_set_text(ui_lblWifiStatus, s_last_status);
    }
}

static void wifi_textarea_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *ta = lv_event_get_target(e);

    if (!ui_kbWifi)
    {
        return;
    }

    if (code == LV_EVENT_FOCUSED)
    {
        lv_keyboard_set_textarea(ui_kbWifi, ta);
        lv_obj_clear_flag(ui_kbWifi, LV_OBJ_FLAG_HIDDEN);
    }
}

static void wifi_keyboard_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (!ui_kbWifi)
    {
        return;
    }

    if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL)
    {
        lv_obj_add_flag(ui_kbWifi, LV_OBJ_FLAG_HIDDEN);
        lv_keyboard_set_textarea(ui_kbWifi, NULL);
    }
}

static void enable_gesture_bubble_recursive(lv_obj_t *parent)
{
    uint32_t child_count = lv_obj_get_child_count(parent);
    for (uint32_t i = 0; i < child_count; i++)
    {
        lv_obj_t *child = lv_obj_get_child(parent, i);
        lv_obj_add_flag(child, LV_OBJ_FLAG_GESTURE_BUBBLE);
        enable_gesture_bubble_recursive(child);
    }
}

void ui_event_btnWiFiConnect(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        const char *ssid = ui_taWifiSsid ? lv_textarea_get_text(ui_taWifiSsid) : NULL;
        const char *password = ui_taWifiPassword ? lv_textarea_get_text(ui_taWifiPassword) : NULL;
        wifi_manager_connect_with_credentials(ssid, password);
    }
}

void ui_event_btnWiFiBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
    }
}

static void ui_event_WiFiScreen(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_GESTURE)
    {
        return;
    }

    static uint32_t s_last_nav_ms;
    uint32_t now_ms = lv_tick_get();
    if (now_ms - s_last_nav_ms < 300)
    {
        return;
    }

    lv_indev_t *indev = lv_indev_get_act();
    if (!indev)
    {
        return;
    }

    lv_dir_t dir = lv_indev_get_gesture_dir(indev);
    if (dir == LV_DIR_RIGHT)
    {
        s_last_nav_ms = now_ms;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_WiFiScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiTitle = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_lblWifiTitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblWifiTitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_lblWifiTitle, 0);
    lv_obj_set_y(ui_lblWifiTitle, -195);
    lv_obj_set_align(ui_lblWifiTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiTitle, "WiFi Settings");
    lv_obj_set_style_text_color(ui_lblWifiTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiStatus = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_lblWifiStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblWifiStatus, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_lblWifiStatus, 0);
    lv_obj_set_y(ui_lblWifiStatus, -140);
    lv_obj_set_align(ui_lblWifiStatus, LV_ALIGN_CENTER);
    memset(s_last_status, 0, sizeof(s_last_status));
    lv_label_set_text(ui_lblWifiStatus, wifi_manager_get_status_text());
    lv_obj_set_style_text_color(ui_lblWifiStatus, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_lblSsid = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_lblSsid, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblSsid, LV_SIZE_CONTENT);
    lv_obj_align(ui_lblSsid, LV_ALIGN_CENTER, 0, -105);
    lv_label_set_text(ui_lblSsid, "SSID");
    lv_obj_set_style_text_color(ui_lblSsid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSsid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSsid, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taWifiSsid = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_taWifiSsid, 210);
    lv_obj_set_height(ui_taWifiSsid, 40);
    lv_obj_align(ui_taWifiSsid, LV_ALIGN_CENTER, 0, -70);
    lv_textarea_set_one_line(ui_taWifiSsid, true);
    lv_textarea_set_placeholder_text(ui_taWifiSsid, "Enter WiFi name");

    lv_obj_t *ui_lblPass = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_lblPass, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lblPass, LV_SIZE_CONTENT);
    lv_obj_align(ui_lblPass, LV_ALIGN_CENTER, 0, -20);
    lv_label_set_text(ui_lblPass, "Password");
    lv_obj_set_style_text_color(ui_lblPass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPass, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taWifiPassword = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_taWifiPassword, 210);
    lv_obj_set_height(ui_taWifiPassword, 40);
    lv_obj_align(ui_taWifiPassword, LV_ALIGN_CENTER, 0, 15);
    lv_textarea_set_one_line(ui_taWifiPassword, true);
    lv_textarea_set_password_mode(ui_taWifiPassword, true);
    lv_textarea_set_placeholder_text(ui_taWifiPassword, "(leave empty for open)");

    ui_kbWifi = lv_keyboard_create(ui_WiFiScreen);
    lv_obj_set_width(ui_kbWifi, 240);
    lv_obj_set_height(ui_kbWifi, 155);
    lv_obj_align(ui_kbWifi, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_kbWifi, LV_OBJ_FLAG_HIDDEN);

    ui_btnWiFiConnect = lv_button_create(ui_WiFiScreen);
    lv_obj_set_width(ui_btnWiFiConnect, 170);
    lv_obj_set_height(ui_btnWiFiConnect, 55);
    lv_obj_set_x(ui_btnWiFiConnect, 0);
    lv_obj_set_y(ui_btnWiFiConnect, 75);
    lv_obj_set_align(ui_btnWiFiConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWiFiConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_remove_flag(ui_btnWiFiConnect, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_btnWiFiConnect, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWiFiConnect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWiFiConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_lblConnect = lv_label_create(ui_btnWiFiConnect);
    lv_label_set_text(ui_lblConnect, "Connect");
    lv_obj_center(ui_lblConnect);
    lv_obj_set_style_text_color(ui_lblConnect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConnect, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWiFiBack = lv_button_create(ui_WiFiScreen);
    lv_obj_set_width(ui_btnWiFiBack, 110);
    lv_obj_set_height(ui_btnWiFiBack, 45);
    lv_obj_set_x(ui_btnWiFiBack, 0);
    lv_obj_set_y(ui_btnWiFiBack, 155);
    lv_obj_set_align(ui_btnWiFiBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWiFiBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_remove_flag(ui_btnWiFiBack, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_btnWiFiBack, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWiFiBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWiFiBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_lblBack = lv_label_create(ui_btnWiFiBack);
    lv_label_set_text(ui_lblBack, "Back");
    lv_obj_center(ui_lblBack);
    lv_obj_set_style_text_color(ui_lblBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBack, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Allow gestures that start on children to bubble up to the screen.
    enable_gesture_bubble_recursive(ui_WiFiScreen);
    lv_obj_add_event_cb(ui_WiFiScreen, ui_event_WiFiScreen, LV_EVENT_GESTURE, NULL);

    lv_obj_add_event_cb(ui_taWifiSsid, wifi_textarea_event_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taWifiPassword, wifi_textarea_event_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_kbWifi, wifi_keyboard_event_cb, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_btnWiFiConnect, ui_event_btnWiFiConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWiFiBack, ui_event_btnWiFiBack, LV_EVENT_ALL, NULL);

    // Poll WiFi status from UI thread (safe); avoid redrawing when unchanged.
    if (!s_wifi_status_timer)
    {
        s_wifi_status_timer = lv_timer_create(wifi_status_timer_cb, 300, NULL);
    }
    wifi_status_timer_cb(NULL);
}

void ui_WiFiScreen_screen_destroy(void)
{
    if (ui_WiFiScreen)
        lv_obj_del(ui_WiFiScreen);

    if (s_wifi_status_timer)
    {
        lv_timer_del(s_wifi_status_timer);
        s_wifi_status_timer = NULL;
    }

    ui_WiFiScreen = NULL;
    ui_btnWiFiConnect = NULL;
    ui_btnWiFiBack = NULL;
    ui_lblWifiTitle = NULL;
    ui_lblWifiStatus = NULL;

    ui_taWifiSsid = NULL;
    ui_taWifiPassword = NULL;
    ui_kbWifi = NULL;
}
