// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_FontDate = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Bar2 = NULL;lv_obj_t *ui_batLBL = NULL;lv_obj_t *ui_btnSettings = NULL;lv_obj_t *ui_lblSteps = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_lblAlertCount = NULL;
// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      startRescueSequence( e );
}
}

void ui_event_btnSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_SettingsScreen_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -45 );
lv_obj_set_y( ui_Label1, -201 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Res");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 28 );
lv_obj_set_y( ui_Label2, -199 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Q+");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -23 );
lv_obj_set_y( ui_Label3, -41 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"10:09");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_FontTimeBig, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FontDate = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_FontDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FontDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FontDate, -9 );
lv_obj_set_y( ui_FontDate, 27 );
lv_obj_set_align( ui_FontDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_FontDate,"MON, JAN 31");
lv_obj_set_style_text_color(ui_FontDate, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FontDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FontDate, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 149 );
lv_obj_set_y( ui_Label6, -28 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"35");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_FontTimeSmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 161);
lv_obj_set_height( ui_Button1, 44);
lv_obj_set_x( ui_Button1, 56 );
lv_obj_set_y( ui_Button1, 119 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button1, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xB80000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Button1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Button1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 39);
lv_obj_set_height( ui_Panel3, 38);
lv_obj_set_x( ui_Panel3, -1 );
lv_obj_set_y( ui_Panel3, 119 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 1 );
lv_obj_set_y( ui_Label7, 119 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"+");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 80 );
lv_obj_set_y( ui_Label9, 117 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Alert");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Screen1);
lv_bar_set_mode(ui_Bar2, LV_BAR_MODE_RANGE);
lv_bar_set_value(ui_Bar2,100,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 69);
lv_obj_set_height( ui_Bar2, 21);
lv_obj_set_x( ui_Bar2, -134 );
lv_obj_set_y( ui_Bar2, 210 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x6A36CF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar2,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar2, lv_obj_get_style_pad_right(ui_Bar2,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_batLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batLBL, -133 );
lv_obj_set_y( ui_batLBL, 210 );
lv_obj_set_align( ui_batLBL, LV_ALIGN_CENTER );
lv_label_set_text(ui_batLBL,"100%");
lv_obj_set_style_text_color(ui_batLBL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batLBL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batLBL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnSettings = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_btnSettings, 53);
lv_obj_set_height( ui_btnSettings, 53);
lv_obj_set_x( ui_btnSettings, -120 );
lv_obj_set_y( ui_btnSettings, 121 );
lv_obj_set_align( ui_btnSettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnSettings, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_btnSettings, &ui_img_200884385, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_lblSteps = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblSteps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblSteps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblSteps, 86 );
lv_obj_set_y( ui_lblSteps, 210 );
lv_obj_set_align( ui_lblSteps, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblSteps,"0");
lv_obj_set_style_text_color(ui_lblSteps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblSteps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblSteps, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image1, &ui_img_rsz_1running_4390015_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Image1, 127 );
lv_obj_set_y( ui_Image1, 201 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblAlertCount = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblAlertCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAlertCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAlertCount, 143 );
lv_obj_set_y( ui_lblAlertCount, 72 );
lv_obj_set_align( ui_lblAlertCount, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAlertCount,"0");
lv_obj_set_style_text_color(ui_lblAlertCount, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblAlertCount, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblAlertCount, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnSettings, ui_event_btnSettings, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Label3= NULL;
ui_FontDate= NULL;
ui_Label6= NULL;
ui_Button1= NULL;
ui_Panel3= NULL;
ui_Label7= NULL;
ui_Label9= NULL;
ui_Bar2= NULL;
ui_batLBL= NULL;
ui_btnSettings= NULL;
ui_lblSteps= NULL;
ui_Image1= NULL;
ui_lblAlertCount= NULL;

}
